spring.application.name=ProductService

server.port=7072

# PostgreSQL connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/Inventory
spring.datasource.username=postgres
spring.datasource.password=Suvam@123
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional: Hibernate JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka


#Kafka
# Kafka bootstrap server
spring.kafka.bootstrap-servers=localhost:9092

# Key serializer for Long type
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.LongSerializer

# Value serializer for custom object (JSON)
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.properties.spring.json.add.type.headers=false

#JWT
jwt.secret=3YK5V9xiYbtl5rZrFUitUBwWjKJNEBAkZ7uspA5B8VG
