spring.application.name=InventoryService

server.port=7073

# PostgreSQL connection settings
spring.datasource.url=jdbc:postgresql://localhost:5432/Inventory
spring.datasource.username=postgres
spring.datasource.password=Suvam@123
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional: Hibernate JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka


# Kafka
# Kafka bootstrap server
spring.kafka.bootstrap-servers=localhost:9092

# Consumer group ID
spring.kafka.consumer.group-id=inventory-service-group

# Enable error-handling deserializer for key
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.LongDeserializer

# Enable error-handling deserializer for value
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# Specify the target class for JSON deserialization
spring.kafka.consumer.properties.spring.json.value.default.type=com.inventory.InventoryService.Utilites.ProductQuantityMessage

# Trust all packages (or specify yours)
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.consumer.auto-offset-reset=earliest

#JWT
jwt.secret=3YK5V9xiYbtl5rZrFUitUBwWjKJNEBAkZ7uspA5B8VG

